### ISSUE TITLE
Can you update the course?

### ISSUE THREAD

**Issue by Gazoon007** [ronhedwigzape/vueschool-free-courses#1]
Especially for Nuxt? Thanks

**Comment by ronhedwigzape** [comment]
Okay, maybe i'll try to upload some. Thanks for the feedback!

**Comment by ronhedwigzape** [comment]
Had a new update from Mastering Nuxt 3 (2023 update): https://drive.google.com/drive/folders/1YiuZ29Z9bq8TAZWwi3lE1rKjena65o_9?usp=sharing
